/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Util;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.log4j.Logger;

/**
 *
 * @author Jesús
 */
public class SellingMenu extends MyOwnJFrame {
    private final static Logger log = Logger.getLogger(SellingMenu.class);
    /**
     * Creates new form SellingMenu
     */
    public SellingMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        int i;
        
        for(i=0; i<Util.totalCategories; i++){
            jComboBoxCategory.addItem(Util.CATEGORY[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneSelectCategory = new javax.swing.JTabbedPane();
        jPanelCategory = new javax.swing.JPanel();
        jLabelChooseCategory = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox();
        jButtonNext = new javax.swing.JButton();
        jPanelCustomize = new javax.swing.JPanel();
        jLabelProductName = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelPrice = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPaneDescription = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelUploadImages = new javax.swing.JLabel();
        jTextFieldImagePath = new javax.swing.JTextField();
        jButtonImagePath = new javax.swing.JButton();
        jButtonFinish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneSelectCategory.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jPanelCategory.setEnabled(false);

        jLabelChooseCategory.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelChooseCategory.setText("Choose the product type:");

        jComboBoxCategory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButtonNext.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonNext.setText("Next");

        javax.swing.GroupLayout jPanelCategoryLayout = new javax.swing.GroupLayout(jPanelCategory);
        jPanelCategory.setLayout(jPanelCategoryLayout);
        jPanelCategoryLayout.setHorizontalGroup(
            jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelChooseCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(jButtonNext)
                .addContainerGap())
        );
        jPanelCategoryLayout.setVerticalGroup(
            jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelChooseCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNext))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jTabbedPaneSelectCategory.addTab("Select Category", jPanelCategory);

        jPanelCustomize.setFocusable(false);

        jLabelProductName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelProductName.setText("Product Name:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelPrice.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelPrice.setText("Price (BsF):");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Description:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPaneDescription.setViewportView(jTextArea1);

        jLabelUploadImages.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelUploadImages.setText("Upload Images:");

        jButtonImagePath.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonImagePath.setText(". . .");
        jButtonImagePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImagePathActionPerformed(evt);
            }
        });

        jButtonFinish.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonFinish.setText("Finish");

        javax.swing.GroupLayout jPanelCustomizeLayout = new javax.swing.GroupLayout(jPanelCustomize);
        jPanelCustomize.setLayout(jPanelCustomizeLayout);
        jPanelCustomizeLayout.setHorizontalGroup(
            jPanelCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneDescription)
                    .addGroup(jPanelCustomizeLayout.createSequentialGroup()
                        .addGroup(jPanelCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabelProductName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextFieldPrice)))
                    .addGroup(jPanelCustomizeLayout.createSequentialGroup()
                        .addComponent(jLabelUploadImages)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonImagePath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jButtonFinish)))
                .addContainerGap())
        );
        jPanelCustomizeLayout.setVerticalGroup(
            jPanelCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProductName)
                    .addComponent(jLabelPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUploadImages)
                    .addComponent(jTextFieldImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonImagePath)
                    .addComponent(jButtonFinish))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneSelectCategory.addTab("Customize", jPanelCustomize);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneSelectCategory)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneSelectCategory)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImagePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImagePathActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        jfc.setFileFilter(imageFilter);
        int r = jfc.showOpenDialog(null);
        if(r == JFileChooser.APPROVE_OPTION){
            try{
                File f = jfc.getSelectedFile();
                String fileName = f.getAbsolutePath();
                jTextFieldImagePath.setText(fileName);
            }catch(Exception e){
                log.warn("Excepción: " + e);
            }
        }
    }//GEN-LAST:event_jButtonImagePathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellingMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFinish;
    private javax.swing.JButton jButtonImagePath;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JComboBox jComboBoxCategory;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelChooseCategory;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelProductName;
    private javax.swing.JLabel jLabelUploadImages;
    private javax.swing.JPanel jPanelCategory;
    private javax.swing.JPanel jPanelCustomize;
    private javax.swing.JScrollPane jScrollPaneDescription;
    private javax.swing.JTabbedPane jTabbedPaneSelectCategory;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldImagePath;
    private javax.swing.JTextField jTextFieldPrice;
    // End of variables declaration//GEN-END:variables
}
