/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.SignUp2Controller;
import controller.Util;
import org.apache.log4j.Logger;

/**
 *
 * @author Jesús
 */
public class SignUp2 extends MyOwnJFrame {
    private final static Logger log = Logger.getLogger(SignUp2.class);
    private final SignUp2Controller sgn2c = new SignUp2Controller();
    /**
     * Creates new form SignIn2
     */
    public SignUp2() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        jComboBoxMonth = sgn2c.setComboMonth(jComboBoxMonth);
        jComboBoxDay = sgn2c.setComboDay(jComboBoxDay);
        jComboBoxYear = sgn2c.setComboYear(jComboBoxYear);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSignIn2 = new javax.swing.JLabel();
        jLabelEMail = new javax.swing.JLabel();
        jTextFieldEMail = new javax.swing.JTextField();
        jLabelBirthDate = new javax.swing.JLabel();
        jComboBoxMonth = new javax.swing.JComboBox();
        jComboBoxYear = new javax.swing.JComboBox();
        jComboBoxDay = new javax.swing.JComboBox();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabelRewritePassword = new javax.swing.JLabel();
        jPasswordFieldRewritePassword = new javax.swing.JPasswordField();
        jButtonDone = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelSignIn2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelSignIn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSignIn2.setText("Sign Up");

        jLabelEMail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelEMail.setText("E-Mail:");

        jTextFieldEMail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldEMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEMailKeyTyped(evt);
            }
        });

        jLabelBirthDate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelBirthDate.setText("Birth Date:");

        jComboBoxMonth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBoxYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBoxDay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelPassword.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelPassword.setText("Password:");

        jPasswordFieldPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordFieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldPasswordKeyTyped(evt);
            }
        });

        jLabelRewritePassword.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelRewritePassword.setText("Rewrite Password:");

        jPasswordFieldRewritePassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordFieldRewritePassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldRewritePasswordKeyTyped(evt);
            }
        });

        jButtonDone.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonDone.setText("Done");
        jButtonDone.setEnabled(false);
        jButtonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoneActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSignIn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(63, 63, 63))
                            .addComponent(jTextFieldEMail)
                            .addComponent(jLabelBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldPassword)
                            .addComponent(jLabelRewritePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldRewritePassword))
                        .addGap(0, 180, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDone)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSignIn2)
                .addGap(18, 18, 18)
                .addComponent(jLabelEMail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabelBirthDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRewritePassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldRewritePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDone)
                    .addComponent(jButtonBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.restoreFatherWindow();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        this.restoreFatherWindow();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoneActionPerformed
        // TODO add your handling code here:
        boolean validEmail, validPasswordLength, equalPassword;
        Util.actualUser.setEmail(jTextFieldEMail.getText());
        Util.actualUser.setPassword(jPasswordFieldPassword.getText());
        
        validEmail = sgn2c.validateEmail(Util.actualUser.getEmail());
        validPasswordLength = sgn2c.passwordLengthIsCorrect(Util.actualUser.getPassword());
        equalPassword = sgn2c.equalStrings(Util.actualUser.getPassword(), jPasswordFieldRewritePassword.getText());
        
        if(validEmail && validPasswordLength && equalPassword){
            sgn2c.saveUserInDataBase(Util.actualUser);
            Util.done = true;
            this.restoreFatherWindow();
        }
    }//GEN-LAST:event_jButtonDoneActionPerformed

    private void jTextFieldEMailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEMailKeyTyped
        // TODO add your handling code here:
        String email = jTextFieldEMail.getText();
        String password = jPasswordFieldPassword.getText();
        String passwordRewritten = jPasswordFieldRewritePassword.getText();
        
        if(!email.equals("") && !password.equals("") && !passwordRewritten.equals("")){
            jButtonDone.setEnabled(true);
        }else{
            jButtonDone.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldEMailKeyTyped

    private void jPasswordFieldPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordKeyTyped
        // TODO add your handling code here:
        String email = jTextFieldEMail.getText();
        String password = jPasswordFieldPassword.getText();
        String passwordRewritten = jPasswordFieldRewritePassword.getText();
        
        if(!email.equals("") && !password.equals("") && !passwordRewritten.equals("")){
            jButtonDone.setEnabled(true);
        }else{
            jButtonDone.setEnabled(false);
        }
    }//GEN-LAST:event_jPasswordFieldPasswordKeyTyped

    private void jPasswordFieldRewritePasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldRewritePasswordKeyTyped
        // TODO add your handling code here:
        String email = jTextFieldEMail.getText();
        String password = jPasswordFieldPassword.getText();
        String passwordRewritten = jPasswordFieldRewritePassword.getText();
        
        if(!email.equals("") && !password.equals("") && !passwordRewritten.equals("")){
            jButtonDone.setEnabled(true);
        }else{
            jButtonDone.setEnabled(false);
        }
    }//GEN-LAST:event_jPasswordFieldRewritePasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDone;
    private javax.swing.JComboBox jComboBoxDay;
    private javax.swing.JComboBox jComboBoxMonth;
    private javax.swing.JComboBox jComboBoxYear;
    private javax.swing.JLabel jLabelBirthDate;
    private javax.swing.JLabel jLabelEMail;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRewritePassword;
    private javax.swing.JLabel jLabelSignIn2;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JPasswordField jPasswordFieldRewritePassword;
    private javax.swing.JTextField jTextFieldEMail;
    // End of variables declaration//GEN-END:variables
}
